#!/bin/bash

echo "
--- Find Command ---

find . -type f -exec grep -i -I “PASSWORD\|PASSWD” {} /dev/null \;

--- Grep Command ---

grep -color=auto -rnw '/' -ie "PASSWORD\|PASSWD" 'color=always 2> /dev/null

"