#!/bin/bash

echo "
-----------------
-- Command
-----------------
1. find . -type f -exec grep -i -I “PASSWORD\|PASSWD” {} /dev/null \;
2. grep -color=auto -rnw '/' -ie "PASSWORD\|PASSWD" 'color=always 2> /dev/null
3. locate <filename>

-----------------
-- Details
-----------------
Once a foothold has been gained on a server, utilize the above commands to search common areas
or for text indicating exposed credentials.
"