#!/bin/bash

if [ -d "~/tools/jwt_tool" ]; then
  echo "JWT Tool is already installed at ~/tools/jwt_tool"
  return
fi

cd ~/tools

git clone https://github.com/ticarpi/jwt_tool.git
cd jwt_tool
pip3 install -r "requirements"