#!/bin/bash

if [ -d "~/tools/RsaCtfTool" ]; then
  echo "RsaCtfTool is already installed at ~/tools/RsaCtfTool"
  return
fi

cd ~/tools

git clone https://github.com/RsaCtfTool/RsaCtfTool.git
sudo apt-get install libgmp3-dev libmpc-dev 
cd RsaCtfTool
pip3 install -r "requirements.txt"