#!/bin/bash

if [ -d "~/tools/snmpbw" ]; then
  echo "SNMPBW is already installed at ~/tools/snmpbw"
  return
fi

cd ~/tools
mkdir snmpbw
cd snmpbw

wget -N https://raw.githubusercontent.com/dheiland-r7/snmp/refs/heads/master/snmpbw.pl
chmod +x snmpbw.pl