#!/bin/bash

# Script to install Feroxbuster
if [ -d "~/tools/feroxbuster" ]; then
  echo "Feroxbuster is already installed at ~/tools/feroxbuster"
  return
fi

# Update package list and install dependencies
sudo apt-get update
sudo apt-get install -y curl

# Download the latest release of Feroxbuster
cd ~/tools
mkdir feroxbuster
cd feroxbuster

curl -sL https://raw.githubusercontent.com/epi052/feroxbuster/main/install-nix.sh | bash -s $HOME/.local/bin